"""
Concurrent Sandbox Server

FastAPI server exposing sandbox execution endpoints.
Port: 7332
"""

import asyncio
import json
import os
import sys
from datetime import datetime
from typing import Dict, Any, List, Optional

from fastapi import FastAPI, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# Add parent to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from engine.executor.code_executor import get_executor, execute_code
from engine.validator.llm_code_validator import get_validator, validate_code
from engine.sandbox.topology_builder import TopologyBuilder
from engine.sandbox.runtime_pool import get_runtime_pool


# ============================================================================
# Models
# ============================================================================

class ExecuteRequest(BaseModel):
    """Request model for code execution"""
    code: str
    language: str = "python"
    stdin: Optional[str] = ""
    timeout: int = 10


class ExecuteResponse(BaseModel):
    """Response model for code execution"""
    stdout: str
    stderr: str
    exit_code: int
    runtime_ms: float
    cpu_usage_pct: float
    mem_peak_mb: float
    timed_out: bool
    slot_id: int


class ValidateRequest(BaseModel):
    """Request model for code validation"""
    prompt: str
    code: str
    language: Optional[str] = None
    expected_output: Optional[str] = None
    timeout: int = 10


class ValidateResponse(BaseModel):
    """Response model for validation"""
    result: str  # PASS, FAIL_RUNTIME, FAIL_TIMEOUT, FAIL_OUTPUT, FAIL_SYNTAX
    stdout: str
    stderr: str
    exit_code: int
    retry_count: int
    runtime_ms: float


class StatsResponse(BaseModel):
    """Response model for statistics"""
    pool_stats: Dict[str, Any]
    executor_stats: Dict[str, Any]
    validation_stats: Dict[str, Any]


# ============================================================================
# FastAPI App
# ============================================================================

app = FastAPI(
    title="Concurrent Sandbox API",
    description="32-thread concurrent code execution sandbox",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Global state
_initialized = False


async def initialize_app():
    """Initialize sandbox systems"""
    global _initialized
    if _initialized:
        return
    
    print("Initializing sandbox...")
    
    # Build topology
    builder = TopologyBuilder()
    builder.build_and_save()
    
    # Initialize runtime pool
    await get_runtime_pool()
    
    # Initialize executor
    await get_executor()
    
    # Initialize validator
    await get_validator()
    
    _initialized = True
    print("Sandbox initialized")


@app.on_event("startup")
async def startup():
    """Startup event"""
    await initialize_app()


# ============================================================================
# Endpoints
# ============================================================================

@app.get("/health")
async def health_check():
    """Health check endpoint"""
    return {
        "status": "healthy" if _initialized else "initializing",
        "timestamp": datetime.now().isoformat()
    }


@app.post("/execute", response_model=ExecuteResponse)
async def execute(request: ExecuteRequest):
    """
    Execute code in sandboxed environment.
    
    - **code**: Source code to execute
    - **language**: Programming language (python, node, bash, go, rust, etc.)
    - **stdin**: Optional standard input
    - **timeout**: Maximum execution time in seconds
    """
    try:
        result = await execute_code(
            request.code,
            request.language,
            request.stdin or "",
            request.timeout
        )
        
        return ExecuteResponse(
            stdout=result.stdout,
            stderr=result.stderr,
            exit_code=result.exit_code,
            runtime_ms=result.runtime_ms,
            cpu_usage_pct=result.cpu_usage_pct,
            mem_peak_mb=result.mem_peak_mb,
            timed_out=result.timed_out,
            slot_id=result.slot_id
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/validate", response_model=ValidateResponse)
async def validate(request: ValidateRequest):
    """
    Validate code generated by LLM.
    
    - **prompt**: Original prompt that generated the code
    - **code**: Code to validate
    - **language**: Programming language (auto-detected if None)
    - **expected_output**: Expected output for validation
    - **timeout**: Execution timeout in seconds
    """
    try:
        record = await validate_code(
            request.prompt,
            request.code,
            request.language,
            request.expected_output
        )
        
        return ValidateResponse(
            result=record.result.value,
            stdout=record.execution_result.stdout if record.execution_result else "",
            stderr=record.execution_result.stderr if record.execution_result else "",
            exit_code=record.execution_result.exit_code if record.execution_result else -1,
            retry_count=record.retry_count,
            runtime_ms=record.execution_result.runtime_ms if record.execution_result else 0
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/stats", response_model=StatsResponse)
async def get_stats():
    """Get sandbox statistics"""
    try:
        pool = await get_runtime_pool()
        executor = await get_executor()
        validator = await get_validator()
        
        return StatsResponse(
            pool_stats=pool.get_stats(),
            executor_stats=executor.get_stats(),
            validation_stats=validator.get_stats()
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/topology")
async def get_topology():
    """Get sandbox topology configuration"""
    topology_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "config", "sandbox_topology.json"
    )
    
    if os.path.exists(topology_path):
        with open(topology_path, "r") as f:
            return json.load(f)
    
    raise HTTPException(status_code=404, detail="Topology not found")


@app.post("/initialize")
async def initialize():
    """Re-initialize sandbox (rebuild topology, warm slots)"""
    await initialize_app()
    return {"status": "initialized"}


# ============================================================================
# Main Entry Point
# ============================================================================

if __name__ == "__main__":
    import uvicorn
    
    uvicorn.run(app, host="0.0.0.0", port=7332)
