"""
Phase 4: Qwen3 Validation Harness

Validates code generated by qwen3-coder:30b through sandbox execution.
Classifies results and handles repair loops.
"""

import json
import re
import asyncio
from typing import Dict, Any, List, Optional, Tuple
from pathlib import Path
from datetime import datetime
from dataclasses import dataclass, field
from enum import Enum

# Import from sibling modules
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))
from executor.code_executor import get_executor, ExecutionResult


class ValidationResult(Enum):
    """Classification of validation result"""
    PASS = "PASS"
    FAIL_RUNTIME = "FAIL_RUNTIME"
    FAIL_TIMEOUT = "FAIL_TIMEOUT"
    FAIL_OUTPUT = "FAIL_OUTPUT"
    FAIL_SYNTAX = "FAIL_SYNTAX"


@dataclass
class ValidationRecord:
    """Record of a single validation attempt"""
    prompt: str
    generated_code: str
    language: str
    expected_output: Optional[str]
    result: ValidationResult
    execution_result: Optional[ExecutionResult]
    retry_count: int
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "prompt": self.prompt[:200] if len(self.prompt) > 200 else self.prompt,
            "generated_code": self.generated_code[:500] if len(self.generated_code) > 500 else self.generated_code,
            "language": self.language,
            "expected_output": self.expected_output,
            "result": self.result.value,
            "execution_result": self.execution_result.to_dict() if self.execution_result else None,
            "retry_count": self.retry_count,
            "timestamp": self.timestamp
        }


class LLMCodeValidator:
    """
    Validates code generated by qwen3-coder:30b.
    
    Features:
    - Extract code blocks from markdown
    - Execute in sandbox
    - Classify results
    - Generate repair prompts
    - Track statistics
    """
    
    MAX_RETRIES = 2
    STATS_FILE = "state/validation_stats.json"
    
    def __init__(self, stats_path: str = None):
        self.stats_path = Path(stats_path or self.STATS_FILE)
        self.executor = None
        self.stats = self._load_stats()
        self.validation_history: List[ValidationRecord] = []
        
    def _load_stats(self) -> Dict[str, Any]:
        """Load validation statistics"""
        if self.stats_path.exists():
            with open(self.stats_path, "r") as f:
                return json.load(f)
        return {
            "total_executions": 0,
            "successful": 0,
            "failed": 0,
            "timeouts": 0,
            "pass_rate": 0.0,
            "language_stats": {},
            "avg_retries": 0.0,
            "last_updated": None
        }
    
    def _save_stats(self):
        """Save validation statistics"""
        self.stats["last_updated"] = datetime.now().isoformat()
        
        # Calculate pass rate
        if self.stats["total_executions"] > 0:
            self.stats["pass_rate"] = (
                self.stats["successful"] / self.stats["total_executions"]
            )
        
        # Calculate average retries
        total_with_retries = sum(
            1 for r in self.validation_history if r.retry_count > 0
        )
        if total_with_retries > 0:
            self.stats["avg_retries"] = (
                sum(r.retry_count for r in self.validation_history) / 
                total_with_retries
            )
        
        self.stats_path.parent.mkdir(parents=True, exist_ok=True)
        with open(self.stats_path, "w") as f:
            json.dump(self.stats, f, indent=2)
    
    async def initialize(self):
        """Initialize the validator"""
        self.executor = await get_executor()
    
    def extract_code_blocks(self, markdown: str) -> List[Tuple[str, str]]:
        """
        Extract code blocks from markdown.
        
        Returns list of (language, code) tuples.
        """
        # Pattern for fenced code blocks
        pattern = r'```(\w+)?\n(.*?)```'
        matches = re.findall(pattern, markdown, re.DOTALL)
        
        code_blocks = []
        for lang, code in matches:
            language = lang.strip() if lang else "python"  # Default to python
            code_blocks.append((language, code.strip()))
        
        # If no code blocks found, treat entire text as code
        if not code_blocks and markdown.strip():
            code_blocks.append(("python", markdown.strip()))
        
        return code_blocks
    
    def detect_language(self, code: str) -> str:
        """Heuristically detect programming language"""
        # Check for common patterns
        if "import " in code and "def " in code:
            return "python"
        if "function " in code or "const " in code or "console.log" in code:
            return "node"
        if "package main" in code and "func main" in code:
            return "go"
        if "fn main" in code:
            return "rust"
        if "#include" in code and "int main" in code:
            return "g++"
        if "echo " in code or "export " in code:
            return "bash"
        
        return "python"  # Default
    
    async def validate(
        self,
        prompt: str,
        generated_code: str,
        language: str = None,
        expected_output: str = None,
        timeout: int = 10
    ) -> ValidationRecord:
        """
        Validate generated code through execution.
        
        Args:
            prompt: Original prompt that generated the code
            generated_code: Code to validate
            language: Programming language (auto-detected if None)
            expected_output: Expected output for validation
            timeout: Execution timeout in seconds
            
        Returns:
            ValidationRecord with result classification
        """
        if not language:
            language = self.detect_language(generated_code)
        
        retry_count = 0
        current_code = generated_code
        last_result = None
        
        while retry_count <= self.MAX_RETRIES:
            # Execute code
            exec_result = await self.executor.execute(
                current_code,
                language,
                timeout=timeout
            )
            
            # Classify result
            result = self._classify_result(
                exec_result,
                expected_output
            )
            
            last_result = ValidationRecord(
                prompt=prompt,
                generated_code=current_code,
                language=language,
                expected_output=expected_output,
                result=result,
                execution_result=exec_result,
                retry_count=retry_count
            )
            
            # If passed, we're done
            if result == ValidationResult.PASS:
                break
            
            # If failed, generate repair prompt and retry
            if retry_count < self.MAX_RETRIES:
                repair_prompt = self._create_repair_prompt(
                    prompt, current_code, exec_result, result
                )
                # In full implementation, this would call qwen3-coder:30b
                # For now, we just note the failure
                retry_count += 1
            else:
                break
        
        # Update stats
        self._update_stats(last_result)
        self.validation_history.append(last_result)
        
        return last_result
    
    def _classify_result(
        self,
        exec_result: ExecutionResult,
        expected_output: Optional[str]
    ) -> ValidationResult:
        """Classify execution result"""
        
        if exec_result.timed_out:
            return ValidationResult.FAIL_TIMEOUT
        
        if exec_result.exit_code != 0:
            # Check if it's a syntax error
            stderr_lower = exec_result.stderr.lower()
            if any(x in stderr_lower for x in ["syntax", "parse", "invalid"]):
                return ValidationResult.FAIL_SYNTAX
            return ValidationResult.FAIL_RUNTIME
        
        # If expected output provided, check it
        if expected_output:
            if expected_output.strip() not in exec_result.stdout:
                return ValidationResult.FAIL_OUTPUT
        
        return ValidationResult.PASS
    
    def _create_repair_prompt(
        self,
        original_prompt: str,
        code: str,
        exec_result: ExecutionResult,
        result: ValidationResult
    ) -> str:
        """Create repair prompt for qwen3-coder:30b"""
        
        error_type = result.value
        error_details = exec_result.stderr if exec_result else "Unknown error"
        
        repair_prompt = f"""
Original task: {original_prompt[:500]}

Previous code failed with {error_type}:
```
{code[:1000]}
```

Error output:
{error_details[:500]}

Please fix the code to resolve this issue.
"""
        
        return repair_prompt
    
    def _update_stats(self, record: ValidationRecord):
        """Update validation statistics"""
        self.stats["total_executions"] += 1
        
        if record.result == ValidationResult.PASS:
            self.stats["successful"] += 1
        else:
            self.stats["failed"] += 1
        
        if record.execution_result and record.execution_result.timed_out:
            self.stats["timeouts"] += 1
        
        # Update language stats
        lang = record.language
        if lang not in self.stats["language_stats"]:
            self.stats["language_stats"][lang] = {
                "total": 0,
                "successful": 0,
                "failed": 0
            }
        
        self.stats["language_stats"][lang]["total"] += 1
        if record.result == ValidationResult.PASS:
            self.stats["language_stats"][lang]["successful"] += 1
        else:
            self.stats["language_stats"][lang]["failed"] += 1
        
        # Save stats
        self._save_stats()
    
    async def validate_batch(
        self,
        pairs: List[Dict[str, Any]],
        output_dir: str = "results"
    ) -> List[ValidationRecord]:
        """
        Validate a batch of (prompt, code) pairs.
        
        Args:
            pairs: List of dicts with 'prompt', 'code', 'language', 'expected_output'
            output_dir: Directory to write results
            
        Returns:
            List of ValidationRecord objects
        """
        results = []
        
        # Process in parallel batches of 32 (sandbox capacity)
        batch_size = 32
        
        for i in range(0, len(pairs), batch_size):
            batch = pairs[i:i + batch_size]
            
            tasks = [
                self.validate(
                    pair.get("prompt", ""),
                    pair.get("code", ""),
                    pair.get("language"),
                    pair.get("expected_output"),
                    pair.get("timeout", 10)
                )
                for pair in batch
            ]
            
            batch_results = await asyncio.gather(*tasks, return_exceptions=True)
            
            for j, result in enumerate(batch_results):
                if isinstance(result, Exception):
                    # Create error record
                    error_record = ValidationRecord(
                        prompt=batch[j].get("prompt", "")[:200],
                        generated_code=batch[j].get("code", "")[:200],
                        language=batch[j].get("language", "unknown"),
                        expected_output=None,
                        result=ValidationResult.FAIL_RUNTIME,
                        execution_result=None,
                        retry_count=0
                    )
                    results.append(error_record)
                else:
                    results.append(result)
            
            print(f"Processed batch {i//batch_size + 1}: {len(batch)} items")
        
        # Write results
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        
        results_file = output_path / f"validation_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        with open(results_file, "w") as f:
            json.dump([r.to_dict() for r in results], f, indent=2)
        
        print(f"Results written to: {results_file}")
        
        return results
    
    def get_stats(self) -> Dict[str, Any]:
        """Get current validation statistics"""
        return {
            **self.stats,
            "history_count": len(self.validation_history)
        }


# Global validator instance
_validator: Optional[LLMCodeValidator] = None


async def get_validator() -> LLMCodeValidator:
    """Get or create global validator"""
    global _validator
    if _validator is None:
        _validator = LLMCodeValidator()
        await _validator.initialize()
    return _validator


async def validate_code(
    prompt: str,
    code: str,
    language: str = None,
    expected_output: str = None
) -> ValidationRecord:
    """Convenience function for code validation"""
    validator = await get_validator()
    return await validator.validate(prompt, code, language, expected_output)


if __name__ == "__main__":
    async def main():
        validator = await get_validator()
        
        # Test validation
        print("Testing code validation...")
        
        # Test 1: Valid Python
        record = await validator.validate(
            "Print hello world",
            "print('Hello, World!')",
            "python",
            expected_output="Hello, World!"
        )
        print(f"\nTest 1 (valid python): {record.result.value}")
        print(f"  stdout: {record.execution_result.stdout.strip()}")
        
        # Test 2: Runtime error
        record = await validator.validate(
            "Divide by zero",
            "print(1 / 0)",
            "python"
        )
        print(f"\nTest 2 (runtime error): {record.result.value}")
        
        # Test 3: Timeout
        record = await validator.validate(
            "Infinite loop",
            "while True: pass",
            "python",
            timeout=2
        )
        print(f"\nTest 3 (timeout): {record.result.value}")
        
        # Stats
        print("\nValidation stats:", validator.get_stats())
    
    asyncio.run(main())
